name: CI Workflow for Darknet

on:
  push:
    branches:
      - master
      - v4
      - v5
  pull_request:
    branches:
      - master
      - v4
      - v5

jobs:
  build:
    runs-on: codeberg-tiny

    steps:
      - uses: https://code.forgejo.org/actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run a script
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake git pkg-config libopencv-dev libopenblas64-0 libopenblas64-0-openmp libopenblas64-openmp-dev
          mkdir -p build
          cd build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build build --parallel
          cmake --build build --target package
          sudo dpkg -i darknet*.deb
          darknet --version
